### PR TITLE
Update Service Bus SDK to T2

### PR DESCRIPTION
**Pull request by wantedfast**

### CODE REVIEW

**Comment by FrankieTF** [comment]
Heaths has reviewed this in another [PR-Azure-Samples/key-vault-dotnet-manage-key-vaults#8](https://github.com/Azure-Samples/key-vault-dotnet-manage-key-vaults/pull/8)
we decide to use await for async code, followed by .ConfigureAwait(false).

**Comment by FrankieTF** [comment]
Heaths has reviewed this in another [PR-Azure-Samples/key-vault-dotnet-manage-key-vaults#8](url)
we decide to use await for async code, followed by .ConfigureAwait(false).

**Comment by FrankieTF** [comment]
Heaths has reviewed this in another [PR-Azure-Samples/key-vault-dotnet-manage-key-vaults#8](url)
we decide to use await for async code, followed by .ConfigureAwait(false).

**Comment by FrankieTF** [comment]
Heaths has reviewed this in another [PR-Azure-Samples/key-vault-dotnet-manage-key-vaults#8](url)
we decide to use await for async code, followed by .ConfigureAwait(false).

**Comment by jongio** [comment]
@jsquire - Can you review please?

**Comment by jsquire** [comment]
I'm going to avoid going through a lot of the detail here, as I think this sample mirrors the feedback that I left in another.     Please see my thoughts in [this](https://github.com/Azure/azure-sdk-for-net/blob/Azure.Messaging.ServiceBus_7.0.0/sdk/servicebus/Azure.Messaging.ServiceBus/samples/Sample07_CrudOperations.md) sample.   To reflect the most important bits:

> The sample is unfocused;  it's not sure whether it wants to show off a management library or a client library.   We should be working against a tight focus and adapting the sample to that purpose.   In either case, we should not be using `Fluent` as it is no longer under active development and is only receiving critical fixes.
>
> If this sample is attempting to demonstrate "how do you create Service Bus resources using the management libraries" then we should strip out the `Azure.Messaging.ServiceBus` use and wait to update until `Azure.ResourceManager.ServiceBus` is available.
>
> If this sample is attempting to demonstrate "how do I use the administration features of `Azure.Messaging.ServiceBus` to create resources like queues and topics in my existing Service Bus namespace" then we should strip out all Fluent and other management use,  bootstrap using an ARM template to create the namespace and demonstrate the administration client similar to how this [sample](https://github.com/Azure/azure-sdk-for-net/blob/Azure.Messaging.ServiceBus_7.0.0/sdk/servicebus/Azure.Messaging.ServiceBus/samples/Sample07_CrudOperations.md) does.

@jongio: You may want to weigh in here, as I think this is salient to both the core content of the sample as well as the scheduling. Thoughts?

**Review by jsquire — COMMENTED** [review]
Each of the samples in this group are highly redundant.  I don't believe there is much value offered.  If anything, I'd recommend that we improve one with the scenarios that we want to highlight and retire the others.

We'll want to determine the focus of the sample and path forward before doing a deeper review.

**Comment by v-xuto** [comment]
@jsquire - Could you please help us close this PR? Because Wantedfast has resigned and we don't have permissions to modify this PR. We will create a new PR to replace it later.

**Comment by jsquire** [comment]
@CamSoper:  Would you be so kind as to close this out or suggest someone that I could follow-up with?

**Comment by CamSoper** [comment]
@jsquire I don't seem to have any rights to this repo.  [Looks to me](https://repos.opensource.microsoft.com/orgs/Azure-Samples/repos/service-bus-dotnet-manage-publish-subscribe-with-advanced-features) as if you need @selvasingh or @yungezz or someone on their teams.

I'm going to copy/paste this comment on the PRs you needed closed to tag them in on each.

**Comment by v-yilinhu** [comment]
PR https://github.com/Azure-Samples/service-bus-dotnet-manage-publish-subscribe-with-basic-features/pull/3 replaces this PR https://github.com/Azure-Samples/service-bus-dotnet-manage-publish-subscribe-with-basic-features/pull/2, so we can close this PR.

**Pull request closed without merging**
